name: Deploy to ACC on push
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env.acceptance
          echo ENVIRONMENT=${{ secrets.ACCEPTANCE_ENVIRONMENT }} >> .env.acceptance
          echo ANALYTICS_ENABLED=${{ secrets.ACCEPTANCE_ANALYTICS_ENABLED }} >> .env.acceptance
          echo ANALYTICS_GTM_ID=${{ secrets.ACCEPTANCE_ANALYTICS_GTM_ID }} >> .env.acceptance
          echo ANALYTICS_SERVER_URL=${{ secrets.ACCEPTANCE_ANALYTICS_SERVER_URL }} >> .env.acceptance

      - name: Build ACC
        run: 'npm ci && npm run build:acc'

      - name: Deploy ACC
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPT_ORG_ACC }}'
          channelId: live
          projectId: appt-org-acc